
### Python Programming
##### by Narendra Allam
Copyright 2020

# Chapter 10

## Numpy

#### Topics Covering
* Numpy Arrays
    * double dimension arrays
    * resizing, reshaping
    * vector multiplication
    * boolean filtering
    * querying using where() function
    * indexing
    * slicing
    * mean, median, stndard deviation, average
    * Transpose
    * Broadcasting
    
* Nimpy matrix
    * addition, multiplication
    * trnaspose, inverse
    
* Numpy random module

In [ ]:
Data Analysis: Understanding data and reporting
Data Anlytics: Data analysis techniques, tools and infrastructure


#### What's NumPy?
NumPy is a Python extension to add support for large, multi-dimensional arrays and matrices,
along with a large library of high-level mathematical functions.


In [ ]:
Data Analysis
-------------
---> 1. Descriptive Analysis (What happend?)
---> 2. Diagnostic Analysis (Why it happend?)
---> 3. Predictive Analysis (What is likely to happen?)
---> 4. Prescriptive Analysis (What course of action to take?) AI

In [ ]:
Particle Attibutes

x
y
z
time
velocity


In [ ]:
x = 20

In [ ]:
import sys
sys.getsizeof(x)

In [ ]:
import numpy as np

In [ ]:
a = np.array([2, 3, 4, 5, 7])

In [ ]:
a

In [7]:
a.shape

(5,)

In [8]:
a.dtype

dtype('int64')

In [9]:
a.ndim

1

In [10]:
a.size

5

In [11]:
a.nbytes

40

In [12]:
a = np.array(range(10))

In [13]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a.dtype

dtype('int64')

In [15]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a = np.array(range(10), dtype=float)
a.dtype

dtype('float64')

__Recommended format__

In [17]:
a = np.array(range(10), dtype='float64')
a.dtype

dtype('float64')

In [16]:
a = np.array(range(10), dtype='d')
a.dtype

dtype('float64')

In [19]:
a.dtype, a.nbytes

(dtype('float64'), 80)

In [7]:
a = np.array((3, 5, 7, 1))
a.dtype, a.nbytes

NameError: name 'np' is not defined

In [6]:
a = np.array((3., 5., .5, 1.))
a.dtype, a.nbytes

NameError: name 'np' is not defined

In [5]:
a = np.array([2+3j, 4+5j])
a.dtype, a.nbytes

NameError: name 'np' is not defined

In [3]:
a = np.array([True, False, True])
a.dtype, a.nbytes

NameError: name 'np' is not defined

In [23]:
a = np.array(['Apple', 'Banana', 'Tender Coconut'])
a.dtype, a.nbytes

(dtype('<U14'), 168)

In [2]:
a

NameError: name 'a' is not defined

In [1]:
print(a)
a.dtype

NameError: name 'a' is not defined

In [24]:
a = np.array(['Apple', 'Banana', 'Tender Coconut'], dtype='U10')
a.dtype, a.nbytes

(dtype('<U10'), 120)

In [25]:
a

array(['Apple', 'Banana', 'Tender Coc'], dtype='<U10')

In [26]:
a = np.array([10, 2.3, 'Apple'])

In [27]:
a, a.dtype

(array(['10', '2.3', 'Apple'], dtype='<U32'), dtype('<U32'))

In [28]:
import numpy as np
a = np.array(range(10), dtype='uint64')

In [29]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint64)

__Multi-dimension arrays:__

In [9]:
l = [2, 3, 4]  # --> 3

l = [[2, 3, 4], 
     [4, 5, 6]]  # --> 2 x 3

l = [[[2, 3, 4], 
       [4, 5, 6]],
      [[2, 3, 4], 
       [4, 5, 6]],
      [[2, 3, 4], 
       [4, 5, 6]]
     ]  # --> 3 x (2 x 3)

l[1][1][2]

6

In [32]:
a = np.array(l)
a.shape

(3, 2, 3)

In [33]:
a

array([[[2, 3, 4],
        [4, 5, 6]],

       [[2, 3, 4],
        [4, 5, 6]],

       [[2, 3, 4],
        [4, 5, 6]]])

In [34]:
l[2][1][1]

5

In [35]:
a[2, 1, 1]

5

####  datatypes

* bool: Boolean (True or False) stored as a bit
* inti: Platform integer (normally either int32 or int64)
* int8: Byte (-128 to 127)
* int16: Integer (-32768 to 32767)
* int32: Integer (-2 ** 31 to 2 ** 31 -1)
* int64: Integer (-2 ** 63 to 2 ** 63 -1)
* uint8: Unsigned integer (0 to 255)
* uint16: Unsigned integer (0 to 65535)
* uint32: Unsigned integer (0 to 2 ** 32 - 1)
* uint64: Unsigned integer (0 to 2 ** 64 - 1)
* float16: Half precision float: sign bit, 5 bits exponent, and 10 bits mantissa
* float32: Single precision float: sign bit, 8 bits exponent, and 23 bits mantissa
* float64 or float: Double precision float: sign bit, 11 bits exponent, and 52 bits mantissa
* complex64 Complex number, represented by two 32-bit floats (real and imaginary components)
* complex128 or complex: Complex number, represented by two 64-bit floats (real and imaginary components)
* SN: String with N ASCII characters,i.e, 'S20', means string with width 20 characters 
* UN: String with N UNICODE characters,i.e, 'U20', means string with width 20 characters

#### dtype Character codes
    Type code   C Type             Minimum size in bytes 
    'b'         signed integer     1 
    'B'         unsigned integer   1 
    'u'         Unicode character  2 (see note) 
    'h'         signed integer     2 
    'H'         unsigned integer   2 
    'i'         signed integer     2 
    'I'         unsigned integer   2 
    'l'         signed integer     4 
    'L'         unsigned integer   4 
    'q'         signed integer     8 (see note) 
    'Q'         unsigned integer   8 (see note) 
    'f'         floating point     4 
    'd'         floating point     8 

In [36]:
np.array(range(10), dtype='H')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint16)

In [13]:
a = np.array(range(1, 11, 3))
a, a.dtype

NameError: name 'np' is not defined

**array() + range()**

In [38]:
a = np.arange(1, 11, 3, dtype='uint32')
print(a)

[ 1  4  7 10]


In [41]:
a = np.empty(4)
print (a.dtype)
print (a)

float64
[3.  5.  0.5 1. ]


In [12]:
a = np.empty((4, 3))
print (a.dtype)
print (a)

NameError: name 'np' is not defined

In [43]:
a = np.empty((4, 3), dtype='int32')
print (a.dtype)
print (a)

int32
[[        0 268435456         0]
 [268435456         3         0]
 [        0         0         0]
 [        0         0    196608]]


In [44]:
a = np.zeros((3, 5), dtype='uint64')
print (a.dtype)
print (a)

uint64
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [45]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
a = np.ones((4, 3, 2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [47]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
a = np.arange(1, 25)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [49]:
a.reshape((4, 3, 2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [50]:
a.reshape((2, 12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [51]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
a

In [52]:
import numpy as np
a = np.arange(24).reshape(4, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [53]:
a.flatten() # flattening to 1-d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a

In [ ]:
a.resize(a.size) # flattening inmemory

In [ ]:
a

In [54]:
a = np.arange(24)
a.resize(4, 3, 2)
al f

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [55]:
b = a.ravel()
print (b) # produces view of the array
c = a.flatten() # takes a copy of the array
print (c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [56]:
# traversing array using ravel
for x in a.ravel():
    print (x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


<b>Note:</b><br>
    The difference is that flatten always returns a copy and ravel returns a view of the original array whenever possible.<br> This isn't visible in the printed output, but if you modify the array returned by ravel, it may modify the entries in the<br> original array. If you modify the entries in an array returned from flatten this will never happen. ravel will often be faster<br> since no memory is copied, but you have to be more careful about modifying the array it returns.

In [57]:
import numpy as np
l = [
    ( 0,  1,  2,  3,  4,  5),
    ( 6,  7,  8,  9, 10, 11),
    [12, 13, 14, 15, 16, 17],
    [18, 19, 20, 21, 22, 23]
    ]
a = np.array(l)

In [58]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

__Accessing Elements__

In [59]:
a[1][4]

10

In [60]:
a[1, 4]

10

__Slicing__

In [61]:
a[1, :5]

array([ 6,  7,  8,  9, 10])

In [62]:
a[:, :4]

array([[ 0,  1,  2,  3],
       [ 6,  7,  8,  9],
       [12, 13, 14, 15],
       [18, 19, 20, 21]])

In [63]:
a[:, -1]

array([ 5, 11, 17, 23])

In [64]:
a[:, ::-1]

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18]])

In [65]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [66]:
a[:, ::-2]

array([[ 5,  3,  1],
       [11,  9,  7],
       [17, 15, 13],
       [23, 21, 19]])

In [67]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [68]:
a[1, 4] = 999
a

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9, 999,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

__Replacing a slice with a value__

In [69]:
a[1, :4] = 999
a

array([[  0,   1,   2,   3,   4,   5],
       [999, 999, 999, 999, 999,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

In [70]:
a[:] = 7
a

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

__Replacing a slice with a sequence__

In [71]:
a = np.arange(24).reshape(4, 6)
a[1, :4] = [55, 88, 77, 66]
a

array([[ 0,  1,  2,  3,  4,  5],
       [55, 88, 77, 66, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

__Replacing a slice with another slice__

In [72]:
a[1, :4] = a[2, 2:]
a

array([[ 0,  1,  2,  3,  4,  5],
       [14, 15, 16, 17, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

__Swapping:__

In [73]:
a = np.arange(1, 25).reshape(4, 6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
a[1, 2] , a[2, 5] =   a[2, 5], a[1, 2]

In [ ]:
a

In [74]:
# Applying math function sin()
c = np.sin(a)
c

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111, -0.99999021,
        -0.53657292],
       [ 0.42016704,  0.99060736,  0.65028784, -0.28790332, -0.96139749,
        -0.75098725],
       [ 0.14987721,  0.91294525,  0.83665564, -0.00885131, -0.8462204 ,
        -0.90557836]])

__Arithmetic__

In [75]:
a = np.array([4, 5, 6, 7, 8])
b = np.array([2, 3, 4, 3, 4])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)

[ 6  8 10 10 12]
[2 2 2 4 4]
[ 8 15 24 21 32]
[2.         1.66666667 1.5        2.33333333 2.        ]
[0 2 2 1 0]


__Querying__

In [77]:
a = np.arange(1, 25).reshape(4, 6)
b = np.sin(a)
print(b)

[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292]
 [ 0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725]
 [ 0.14987721  0.91294525  0.83665564 -0.00885131 -0.8462204  -0.90557836]]


In [79]:
b[b > 0]

array([0.84147098, 0.90929743, 0.14112001, 0.6569866 , 0.98935825,
       0.41211849, 0.42016704, 0.99060736, 0.65028784, 0.14987721,
       0.91294525, 0.83665564])

In [80]:
b > 0

array([[ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False]])

In [81]:
b[b > 0]

array([0.84147098, 0.90929743, 0.14112001, 0.6569866 , 0.98935825,
       0.41211849, 0.42016704, 0.99060736, 0.65028784, 0.14987721,
       0.91294525, 0.83665564])

In [85]:
b[(b > 0) & (b < 1)] = 1
b[(b <= 0)] = 0
b

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

Note: Use paranthesis

__Where exactly this happend ?__

In [ ]:
c = np.sin(np.arange(1, 25).reshape(4, 6))
c

In [ ]:
np.where(c < 0)

In [ ]:
x, y = np.where(c < 0)
list(zip(x, y))

In [ ]:
list(zip(*np.where(c < 0)))

In [ ]:
l = [3, 4 ,5 ,2]
s = 'APPLE'

for x,y in zip(l, s):
    print(x, '->', y)

In [ ]:
x, y = np.where(c < 0)
print ("List of indices where c < 0:")
[(i, j) for i, j in zip(x, y)]

In [ ]:
list(zip(x, y))

In [ ]:
x = np.arange(1, 13).reshape(3, 4)
y = np.arange(13, 25).reshape(3, 4)
x

In [ ]:
y

In [ ]:
b = (x%2 == 0)

In [ ]:
b

In [ ]:
x[b] = y[b]

In [ ]:
x

__Scalar multiplcation__

In [ ]:
c * 10

In [86]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)

In [87]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


__Array addition__

In [88]:
a + b

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

__Element wise multiplication__

In [89]:
a * b

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [90]:
print (a)
print (b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [91]:
a.dot(b) # matrix multiplication

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [92]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [93]:
a.T # transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [94]:
a.std()

2.581988897471611

In [95]:
a.var()

6.666666666666667

In [96]:
a.mean()

5.0

In [97]:
np.average(a)

5.0

In [ ]:
a = np.arange(1,10).reshape(3, 3)
print (a)
a.all()

In [ ]:
a.any()

In [ ]:
any([0, 0, 0, 9, 0])

In [ ]:
all([1, 2, 3, 9, 6])

In [ ]:
a = np.arange(9).reshape(3, 3)
b = np.arange(9, 18).reshape(3, 3)

In [ ]:
print ("----a-----")
print (a)
print ("----b-----")
print (b)
np.hstack((a, b))

In [ ]:
c = np.vstack((a, b))

In [ ]:
c

### Matrices

In [98]:
a = np.mat('4 3 1; 2 1 8; 6 5 4')
b = np.mat([[2, 5, 6], [2, 1, 5], [7, 8, 9]])
c = np.mat(np.arange(9).reshape(3, 3))
a

matrix([[4, 3, 1],
        [2, 1, 8],
        [6, 5, 4]])

In [99]:
b

matrix([[2, 5, 6],
        [2, 1, 5],
        [7, 8, 9]])

In [100]:
c

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [101]:
b.I

matrix([[-0.4025974 ,  0.03896104,  0.24675325],
        [ 0.22077922, -0.31168831,  0.02597403],
        [ 0.11688312,  0.24675325, -0.1038961 ]])

In [ ]:
b.T

In [ ]:
a=np.mat('4 3; 2 1')
b=np.mat('1 2; 3 4')

In [ ]:
a + b

In [ ]:
a * b

#### numpy random module

In [102]:
np.random.rand(10)

array([0.558558  , 0.3209165 , 0.40732292, 0.12912543, 0.56253812,
       0.68652163, 0.34148659, 0.61296653, 0.49603869, 0.39331896])

In [103]:
np.random.randint(1,101, size=10)

array([31, 11, 97, 55, 31, 16, 43,  4, 74, 77])

In [104]:
np.random.randint(1,11, size=20)

array([ 6,  6,  8,  9, 10, 10,  4,  8,  6,  1,  2,  5,  7,  6, 10,  6,  5,
        4,  7,  2])

In [105]:
np.random.randint(1,101, size=10).reshape(2,5)

array([[97, 67,  5, 81, 26],
       [79, 75, 85, 39, 70]])

In [106]:
a = np.mat(np.random.randint(1, 10, size=12).reshape(3, 4))
b = np.mat(np.random.randint(1, 10, size=12).reshape(4, 3))
print (a)
print (b)
print (a * b)

[[3 9 6 5]
 [8 6 7 6]
 [7 8 5 4]]
[[8 4 5]
 [5 8 3]
 [7 2 3]
 [3 9 6]]
[[126 141  90]
 [161 148 115]
 [143 138  98]]


In [ ]:
np.random.random_sample((3, 4))

In [109]:
c = np.random.random_sample((3, 4))
l = c.tolist()
l

[[0.061772624843596136,
  0.05867724472487201,
  0.27310281356286625,
  0.34615929457730155],
 [0.9089941195023267,
  0.5299078967378208,
  0.8959765475604006,
  0.09930307704285224],
 [0.510583113562962,
  0.8657349612100348,
  0.2161744421146461,
  0.06276795375565691]]

In [ ]:
2 x 3. 3 x 3
m x n == p x q
m x q

In [ ]:
c.shape

In [110]:
import numpy as np

a = np.array([5, 3, 1])
c = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
a * c

array([[ 0,  3,  2],
       [15, 12,  5],
       [30, 21,  8]])

In [112]:
c * a

array([[ 0,  3,  2],
       [15, 12,  5],
       [30, 21,  8]])

In [113]:
np.array([5, 3, 1]) * np.array([[0, 1, 2],
                                [3, 4, 5],
                                [6, 7, 8]]) # Broadcasting

array([[ 0,  3,  2],
       [15, 12,  5],
       [30, 21,  8]])

In [114]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [117]:
np.array([[0, 1, 2],
          [3, 4, 5],
          [6, 7, 8]]) * np.array([[5],
                                 [3],
                                 [1]])

array([[ 0,  5, 10],
       [ 9, 12, 15],
       [ 6,  7,  8]])

<b>Broadcasting Rules</b><br>
    In order for an operation to broadcast, the size of all the trailing dimensions for both arrays must either:<br>
    be equal OR one of them must be one <br>
> A (1d array): 3<br>
> B (2d array): 2 x 3<br>

Result (2d array): 2 x 3<br>

> A (2d array): 6 x 1<br>
> B (3d array): 1 x 6 x 4<br>

Result (3d array): 1 x 6 x 4<br>

> A (4d array): 3 x 1 x 6 x 1<br>
> B (3d array): 2 x 1 x 4<br>

Result (4d array): 3 x 2 x 6 x 4<br>

__np.linspace()__ devides the range into n equal partitions and retuns list of points.

In [118]:
np.linspace(1, 100, 15)

array([  1.        ,   8.07142857,  15.14285714,  22.21428571,
        29.28571429,  36.35714286,  43.42857143,  50.5       ,
        57.57142857,  64.64285714,  71.71428571,  78.78571429,
        85.85714286,  92.92857143, 100.        ])